"""Fill the p300c boltz2 exemption reasons this re-record left TODO, and repair the carried
reasons whose evidence half the fresh counts contradict.

Every reason is written as "<evidence>: <judgement>" with the evidence half generated by the
gate's own _size_ladder_reason_evidence, so the head matches SIZE_LADDER_EVIDENCE_HEADS and the
next re-record regenerates the numbers instead of carrying them verbatim. That is the bug the
old text had: "declines every call" is not a head the gate knows, so it travelled with numbers
the entry beside it no longer said.
"""
import importlib.util, json, pathlib, sys

ROOT = pathlib.Path("/home/ttuser/.coworker/wt/tt-bio-sizeladder-p300c-refresh")
spec = importlib.util.spec_from_file_location("rg", ROOT / "scripts" / "release_gate.py")
rg = importlib.util.module_from_spec(spec)
sys.modules["rg"] = rg
spec.loader.exec_module(rg)

MODEL, CARD = "boltz2", "p300c"
ALL = ("256", "512", "640", "768", "896", "1024")

# (flag, rungs) -> judgement half. Verified this pass against tt_bio/ on d35f9db1f and the
# commit that moved each one.
J = {
 ("FP32_SOFTMAX_L1_GRID", ALL):
   "the counter is L1-resident fp32 score blocks and boltz-2 plans none at any size, so the "
   "resolved (8, 8) is the rectangle the constant holds rather than a block that ran. The row "
   "is new because 92d5a9030 gave the rectangle its own l1_blocks/l1_refused counters instead "
   "of scoring it off the bias hoist's",
 ("REBLOCK_PERMUTE_GATED", ("256",)):
   "the gated channel move is only offered once the trimul has moved its pair tensors to DRAM, "
   "and at 256 aa they stay L1-resident, so the gate is never reached here. It serves all 1120 "
   "calls at every rung from 512 up",
 ("FP32_SOFTMAX_BIAS_HOIST", ALL):
   "boltz-2's SDPA bias is bf16, so the fp32 hoist has no call site on this model: 0 served and "
   "0 declined at every rung, on every card",
 ("PAIR_TRANSPOSE_VIA_ROW_MAJOR", ("256", "512", "640")):
   "the row-major route needs a DRAM destination, and through 640 the pair transpose destination "
   "is L1-resident, so TRANSPOSE_L1_RESIDENT serves those calls instead. From 768 up the tensor "
   "stops fitting and this lever serves all 560; exactly one of the two serves at every rung",
 ("TRIMUL_MASK_AFTER_MOVE", ("256",)):
   "it unlocks the gated channel move, which is only offered once the trimul's pair tensors are "
   "in DRAM. At 256 aa they are L1-resident, so nothing is offered here; it serves 1120 at every "
   "rung from 512 up. Default on since 7bfa4ad19",
 ("REBLOCK_PERMUTE", ("512", "640", "768", "896", "1024")):
   "the traffic moved to the gated channel, it did not stop. TRIMUL_MASK_AFTER_MOVE (d86a1eb5f, "
   "default on since 7bfa4ad19) moves the pair mask past the channel move, so the fused "
   "chunk+gate route is eligible and REBLOCK_PERMUTE_GATED now serves the 1120 calls this "
   "counter served when the baseline was recorded. The ungated wrapper is not offered, not "
   "refused",
 # TRANSITION_H_CHUNK is no longer dark at any rung, so it gets no exemption. It read
 # `declined 296, base-unraised` from 512 up when this campaign started; the Blackhole L1 row
 # raise (b81fe4c0a, bounded to c <= 128 by d002db0d9, default on through
 # _TRANSITION_L1_ROWS = env_flag("TT_BIO_TRANSITION_L1_ROWS", True)) now picks a height above
 # the base of 16 on every boltz-2 rung, so the counter serves all 296.
 # Repairs: the carried text claimed declines on entries that now have no calls at all.
 ("PAIR_PROJ_MINIMAL_MATMUL", ("256", "512", "640")):
   "the separate triangle-attention gate projection that fell through to this wrapper is gone. "
   "TRIATT_FUSED_QKVG/QKVGB (07f3d58d0, 887c6d945, default on since 1d1897022) read the normed "
   "pair tensor once for q, k, v, the gate and the bias, so there is no second projection call "
   "to wrap. Where it is still reached, 768 and up, it refuses on k_tiles=4",
 ("PAIR_PROJ_MINIMAL_MATMUL", ("768", "896", "1024")):
   "structurally out of scope for this model: the lever needs an 8-tile weight K dim and "
   "boltz-2's c_z=128 gives 4, so the key reads k_tiles=4 at every call it does see. "
   "Size-independent, so it biases no exponent",
 ("TRIMUL_TAIL_F1", ("512", "640", "768", "896", "1024")):
   "the tail's F1 gate only runs when the output gate was NOT fused into the in-projection, and "
   "TRIMUL_FUSED_GOUT (4963a2c41, default on since 1d1897022) fuses it on the chunked DRAM path "
   "-- every rung from 512 up. At 256 the trimul is L1-resident, the gate is not fused, and F1 "
   "refuses all 560 calls on k_tiles=4",
 ("TRIMUL_TAIL_F1", ("256",)):
   "F1_BLOCK_KEYS allow-lists (8, 8) and boltz-2's trimul tail weight resolves 4 K tiles from "
   "c_hidden, not from N, so F1 is inert on this model at every size rather than dark at this "
   "one",
 # Carried from tt-galaxy-wh, whose residency boundary is one rung lower than this card's: on
 # 11x10 the pair transpose is L1-resident through 640 and falls back from 768 up.
 ("TRANSPOSE_L1_RESIDENT", ("896", "1024")):
   "L1 capacity, not tuning: `_transpose_memory_config` is a static budget with 1.25x headroom "
   "and this card's 11x10 grid has 110 cores of L1, so boltz-2's pair tensor stops fitting from "
   "768 up and the destination goes to DRAM. PAIR_TRANSPOSE_VIA_ROW_MAJOR then serves all 560; "
   "exactly one of the two serves at every rung",
}
# Heads normalised, judgement kept verbatim from the existing reason.
KEEP = [("REBLOCK_PERMUTE", ("256",)),
        ("TRIMUL_IN_PROJ_DUAL_NOC", ("256",)),
        ("REBLOCK_PERMUTE_BACK", ("256",)),
        ("TRANSPOSE_L1_RESIDENT", ("768",))]

path = ROOT / "docs" / "size_ladder_baseline.d" / f"{MODEL}.json"
data = json.loads(path.read_text())
cards = data["cards"]
assert CARD in cards, f"{CARD} missing from the fragment: {sorted(cards)}"
# The other cards' entries must come out byte-identical: this pass re-recorded p300c only.
OTHERS = {c: json.dumps(v, sort_keys=True) for c, v in cards.items() if c != CARD}
levers = cards[CARD]["models"][MODEL]["levers"]

def put(flag, rungs, judgement, source):
    for r in rungs:
        e = levers[r][flag]
        assert rg._size_ladder_dark(e), f"{flag}@{r} is not dark; refusing to annotate it"
        # "declines all 0 calls" is what the gate's generator says for a lever that was never
        # offered; "never reached at this size" is the head it keeps for exactly that case, and
        # it is in SIZE_LADDER_EVIDENCE_HEADS too, so it still regenerates on a re-record.
        head = ("never reached at this size"
                if not (e.get("served") or 0) and not (e.get("declined") or 0)
                else rg._size_ladder_reason_evidence(e))
        assert head.startswith(rg.SIZE_LADDER_EVIDENCE_HEADS), head
        before = e.get("reason", "")
        e["reason"] = f"{head}: {judgement}"
        print(f"  {flag:<28} {r:>4}  [{source}]\n      was: {before[:110]}\n      now: {e['reason'][:110]}")

print("== authored ==")
for (flag, rungs), why in J.items():
    put(flag, rungs, why, "authored")
print("== head normalised, judgement kept ==")
for flag, rungs in KEEP:
    for r in rungs:
        old = levers[r][flag].get("reason", "")
        head, sep, why = old.partition(": ")
        assert sep and why, f"{flag}@{r}: no judgement half to keep in {old!r}"
        put(flag, (r,), why, "kept")

left = rg._size_ladder_unreasoned(levers)
print("\nunreasoned dark levers left:", sorted(left) or "none")
assert not left, left
assert OTHERS == {c: json.dumps(v, sort_keys=True) for c, v in cards.items() if c != CARD}, \
    "a card other than p300c changed"
print("untouched cards verified:", sorted(OTHERS))
path.write_text(json.dumps(data, indent=2) + "\n")
print("written", path)
