"""A 1xN Wormhole mesh graph descriptor, written on demand.

ttnn ships descriptors for the systems it knows (n300 is 1x2, t3k is 2x4) and nothing for a line
of N chips cut out of a 32-chip galaxy. The file is four lines of textproto and the only things
that vary are the arch and the dims, so this generates it rather than checking in eight copies.

`TT_MESH_GRAPH_DESC_PATH` is read when ttnn loads, so `install(N)` must run BEFORE `import ttnn`.
"""

import os
import pathlib

TEMPLATE = """# generated by perf/b2z2_shardscale/meshdesc.py -- a line of {n} {arch} chips
mesh_descriptors {{
  name: "M0"
  arch: {arch}
  device_topology {{ dims: [ {r}, {c} ] }}
  host_topology   {{ dims: [ 1, 1 ] }}
  channels {{ count: {ch} policy: RELAXED }}
}}

top_level_instance {{ mesh {{ mesh_descriptor: "M0" mesh_id: 0 }} }}
"""


def install(n, rows=1, arch="WORMHOLE_B0", channels=2, out_dir="/tmp/b2z2_meshdesc"):
    """Write a rows x (n/rows) descriptor and point TT_MESH_GRAPH_DESC_PATH at it. Returns the path."""
    assert n % rows == 0, f"{n} chips do not fill {rows} rows"
    d = pathlib.Path(out_dir)
    d.mkdir(parents=True, exist_ok=True)
    p = d / f"mesh_{rows}x{n // rows}_{arch.lower()}.textproto"
    p.write_text(TEMPLATE.format(n=n, arch=arch, r=rows, c=n // rows, ch=channels))
    os.environ["TT_MESH_GRAPH_DESC_PATH"] = str(p)
    return str(p)
