"""A 1xN Wormhole mesh graph descriptor, written on demand.

ttnn ships descriptors for the systems it knows (n300 is 1x2, t3k is 2x4) and nothing for a line
of N chips cut out of a 32-chip galaxy. The file is four lines of textproto and the only things
that vary are the arch and the dims, so this generates it rather than checking in eight copies.

`TT_MESH_GRAPH_DESC_PATH` is read when ttnn loads, so `install(N)` must run BEFORE `import ttnn`.
"""

import os
import pathlib

TEMPLATE = """# generated by perf/b2z2_shardscale/meshdesc.py -- a line of {n} {arch} chips
mesh_descriptors {{
  name: "M0"
  arch: {arch}
  device_topology {{ dims: [ {r}, {c} ] }}
  host_topology   {{ dims: [ 1, 1 ] }}
  channels {{ count: {ch} policy: RELAXED }}
}}

top_level_instance {{ mesh {{ mesh_descriptor: "M0" mesh_id: 0 }} }}
"""


def install(n, rows=1, arch="WORMHOLE_B0", channels=2, out_dir="/tmp/b2z2_meshdesc"):
    """Write a rows x (n/rows) descriptor and point TT_MESH_GRAPH_DESC_PATH at it. Returns the path."""
    assert n % rows == 0, f"{n} chips do not fill {rows} rows"
    body = TEMPLATE.format(n=n, arch=arch, r=rows, c=n // rows, ch=channels)
    name = f"mesh_{rows}x{n // rows}_{arch.lower()}.textproto"
    # whglx runs several accounts against one galaxy, so the first worker to ask for a width owns
    # the file and every later one is refused at the write. The contents are a pure function of
    # (n, rows, arch, channels), so an existing file that already says this is the file we wanted;
    # otherwise fall back to a directory this account does own.
    for d in (pathlib.Path(out_dir), pathlib.Path(os.path.expanduser("~/.cache/b2z2_meshdesc"))):
        p = d / name
        if p.is_file() and p.read_text() == body:
            break
        try:
            d.mkdir(parents=True, exist_ok=True)
            p.write_text(body)
            break
        except OSError:
            continue
    else:
        raise RuntimeError(f"could not write a {rows}x{n // rows} mesh descriptor anywhere")
    os.environ["TT_MESH_GRAPH_DESC_PATH"] = str(p)
    return str(p)
