"""The published release notes come from a CHANGELOG heading that nothing checks.

`.github/workflows/release.yaml` builds the GitHub Release body with

    awk -v v="$ver" '/^## /{p=($0 ~ "\\["v"\\]")} p' CHANGELOG.md

and falls back to `gh release create --generate-notes` when that comes back empty. The tag
itself is protected -- the workflow exits 1 when the tag does not match the pyproject version
-- but the heading is not. Bumping the version and leaving `## [Unreleased]` in place still
tags, still builds, still publishes to PyPI, and puts an autogenerated commit list on the
release page in place of the notes written for that release. The first sign of it is the
published page, and by then the notes are the thing users have already read.

So check it one release step earlier: whatever version pyproject declares, CHANGELOG has to
carry a section the workflow's awk can find. Matched the way the workflow matches -- a `## `
heading containing `[<version>]` -- rather than a prettier rule, because a check that reads
the release step differently from the release step is not checking the release step.
"""

import re
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent


def declared_version() -> str:
    """The version the release workflow will compare the tag against."""
    for line in (REPO / "pyproject.toml").read_text().splitlines():
        m = re.match(r'^version *= *"([^"]+)"', line)
        if m:
            return m.group(1)
    raise AssertionError("pyproject.toml declares no version")


def changelog_has_section(version: str) -> bool:
    """True when the workflow's awk would find a section for `version`."""
    return any(f"[{version}]" in h
               for h in re.findall(r"^## .*$", (REPO / "CHANGELOG.md").read_text(), re.M))


def test_changelog_carries_a_section_for_the_declared_version():
    version = declared_version()
    assert changelog_has_section(version), (
        f"pyproject.toml declares version {version} and CHANGELOG.md has no '## [{version}]' "
        f"heading, so tagging v{version} would publish autogenerated commit-list notes instead "
        f"of the written ones. Rename '## [Unreleased]' to '## [{version}] - <date>'.")


def test_the_section_check_can_fail():
    """Control: the check must be able to see a missing section, or its green means nothing."""
    assert not changelog_has_section("0.0.0-no-such-version")
