"""Write the esmfold2 pair-FFN exemption reasons the size-ladder arm asked a human for.

Twenty entries, one mechanism: `PAIR_FFN_ROW_BLOCK_SEQ = (320, 1024)` is an explicit sequence
window, so every lever that only exists inside the row block is unreachable above 1024. The
judgement is written here; the measured half of each reason is regenerated by the gate's own
`_size_ladder_reason_evidence`, so a re-record replaces the numbers and keeps the judgement.
"""
import json
import pathlib
import sys

sys.path.insert(0, "scripts")
import release_gate as rg

FRAG = pathlib.Path("docs/size_ladder_baseline.d/esmfold2.json")
CARD = "p150a"
RUNGS = ("1152", "1280", "1408", "1536")
FALLBACK = (
    "Above the window the block is re-entered only after a real DRAM refusal of the unblocked "
    "FFN (`_UNBLOCKED_REFUSED`, esmc.py:860-870), which did not fire in the run that recorded "
    "this cell; a later run where it does fire reads served > 0 here, and that is the fallback "
    "working rather than drift")
INSIDE = (
    "the pair-FFN row block is bounded by an explicit sequence window, "
    "`PAIR_FFN_ROW_BLOCK_SEQ = (320, 1024)` (tt_bio/esmc.py:320), read on the PADDED token axis "
    "in `_split_plan` (esmc.py:686). Above 1024 `rows` comes back 0, the FFN runs unblocked, and "
    "`_row_blocked` -- the only place this lever exists -- is never entered, so it is not offered "
    "rather than declining. The window is a parity bound, not a tuning choice: 32 rows is pinned "
    "by `torch.equal` and 16 and 8 are faster and NOT bit-exact, so widening it is a release-gate "
    "decision. " + FALLBACK)
RESID = (
    "the same cause counted on the other side of the branch: `residual()` increments this "
    "decline (`FUSED_RESID_STATS[1]`, esmc.py:816) for every call the window sends down the plain "
    "`x + ffn(x)`, and that is every pair transition in the fold. "
    "`PAIR_FFN_ROW_BLOCK_SEQ = (320, 1024)` (esmc.py:320) closes above 1024, so there is no "
    "row-blocked output here to fuse the residual into; 256 aa reads the same way one rung below "
    "the window's lower edge. " + FALLBACK)
JUDGEMENT = {
    "PAIR_FFN_FILL_ASSEMBLY": INSIDE,
    "PAIR_FFN_L1_FC1": INSIDE,
    "PAIR_FFN_L1_LN": INSIDE,
    "PAIR_FFN_L1_SLICE": INSIDE,
    "PAIR_FFN_FUSED_RESIDUAL": RESID,
}

data = json.loads(FRAG.read_text())
levers = data["cards"][CARD]["models"]["esmfold2"]["levers"]
wrote = []
for rung in RUNGS:
    for flag, why in JUDGEMENT.items():
        e = levers[rung][flag]
        assert rg._size_ladder_dark(e), (rung, flag, "not dark -- refusing to annotate")
        old = str(e.get("reason") or "")
        assert not old or old.startswith("TODO"), (rung, flag, "already has a reason: " + old)
        e["reason"] = rg._size_ladder_reason_evidence(e) + ": " + why
        wrote.append((rung, flag, e["reason"][:70]))
FRAG.write_text(json.dumps(data, indent=2) + "\n")
for r, f, head in wrote:
    print("wrote %5s %-24s %s..." % (r, f, head))
print("%d entries" % len(wrote))
