#!/usr/bin/env python3
"""Generate `tt_bio/kernels/trimul_tail/` from the installed wheel's own minimal_matmul kernels.

F1 fuses the trimul output tail's two projections and its gate into one `generic_op`:

    production   layer_norm -> p_out = x_norm @ Wp -> g_out = x_norm_in @ Wg
                            -> multiply_(p_out, g_out, SIGMOID on b)          4P read, 3P write
    F1           layer_norm -> one kernel over (x_norm, Wp) and (x_norm_in, Wg)
                            -> sigmoid + multiply inside the core              2P read, 1P write

At the tail's block config `_MM_BLOCK[8] = (4, 8, 1, 4, 1)` the contraction is one K block
(`K_tiles == K_block_tiles == 8`), so the two GEMMs cannot interact through the cross-block L1
accumulator and the fusion is an extra PASS around the existing inner loop, not a new dataflow:

    for each output block:
        pass 0   K loop on (in0_a, in1_a) -> intermediate_cb -> copy_block -> cb_p   (bf16)
        pass 1   K loop on (in0_b, in1_b) -> intermediate_cb -> copy_block -> cb_g   (bf16)
        gate     sigmoid(cb_g) -> cb_sig ; cb_p * cb_sig -> round bf16 -> cb_out

`x_norm` and `x_norm_in` share shape, dtype, layout and memory config, so both passes share one
`TensorAccessorArgs` and differ only in the base address; likewise the two weights. The second
address rides in the unused `in2_addr` runtime slot, so the arg layout `mm_generic.rebind` depends
on is untouched.

Three rounding points are load-bearing and each mirrors what production does today. Two are E6's,
measured (`tt_bio/kernels/reblock_permute_gated/compute_reblock_permute_gated.cpp`); the third is
new to F1 and exists because F1, unlike E6, must run fp32 DST for the GEMM:

  * p and g are packed from the fp32 accumulator to bf16 through the wheel's own `copy_block`,
    which is the identical pack that writes `p_out` and `g_out` to DRAM today.
  * the sigmoid is instantiated as `llk_math_eltwise_unary_sfpu_sigmoid<false, false>` -- the
    SECOND template argument, not the descriptor's DST width. `sigmoid_tile` hard-wires
    `DST_ACCUM_MODE` and would take the accurate branch, which E6 measured as a full bf16 ulp off
    ttnn on 10.4 % of elements. The bf16 branch ends in `float_to_fp16b(result, 0)`, so what
    reaches the packer is already exactly a bf16 and the pack cannot round it again.
  * the product is rounded to bf16 IN THE SFPU by `round_bf16_tile`, with the same
    `float_to_fp16b(v, 0)`, before it is packed. Under fp32 DST the packer breaks ties away from
    zero where ttnn's 16-bit DST store breaks them to even; E6 measured that as 0.91 % of elements
    at a 1.85 % tie rate. Rounding first makes the pack exact by construction.

Regenerate after any wheel bump: the sources are read from the installed wheel, so a moved anchor
raises here instead of binding a stale kernel silently.
"""
from __future__ import annotations

import sys
from pathlib import Path

OUT = Path(__file__).resolve().parent


def wheel_kernel_dir() -> Path:
    import ttnn
    return (Path(ttnn.__file__).resolve().parent
            / "ttnn/cpp/ttnn/operations/experimental/minimal_matmul/device/kernels")


def sub(text: str, old: str, new: str, what: str, count: int = 1) -> str:
    n = text.count(old)
    if n != count:
        raise SystemExit(f"anchor '{what}' matched {n} times, expected {count}. Wheel moved.")
    return text.replace(old, new, count)


HEADER = """// SPDX-FileCopyrightText: (c) 2026 Tenstorrent USA, Inc.
//
// SPDX-License-Identifier: Apache-2.0
//
// GENERATED by tt_bio/kernels/trimul_tail/patch_trimul_tail.py from the installed wheel's
// minimal_matmul kernels. Do not edit by hand; edit the patch script and regenerate.

#ifndef TRIMUL_TAIL_PASSES
#define TRIMUL_TAIL_PASSES 2
#endif
// How the product is rounded to bf16 before it is packed: 0 leaves it to the packer (which
// breaks ties away from zero under fp32 DST), 1 uses SFPSTOCHRND round-to-nearest-even, 2 does
// the same rounding with integer arithmetic. Only 0 is known-wrong; 1 and 2 are the candidates.
#ifndef TRIMUL_TAIL_ROUND
#define TRIMUL_TAIL_ROUND 2
#endif
// Diagnostic only: drop the gate so the multiply can be scored on its own. Never set in production.
#ifndef TRIMUL_TAIL_SKIP_SIGMOID
#define TRIMUL_TAIL_SKIP_SIGMOID 0
#endif
"""

K_LOOP_CLOSE = """                }
            }
#ifdef FUSE_BIAS"""

K_LOOP_CLOSE_NEW = """                }
            }
            }
#ifdef FUSE_BIAS"""


def patch_in0(src: str) -> str:
    src = sub(src, "const uint32_t in0_addr = get_arg_val<uint32_t>(argidx++);",
              "const uint32_t in0_addr = get_arg_val<uint32_t>(argidx++);\n"
              "    // TRIMUL_TAIL: pass 1's activation rides in the unused in2 slot, so the runtime\n"
              "    // arg layout mm_generic.rebind depends on is unchanged.",
              "in0 addr decl")
    src = sub(src, "const auto in0_reader = TensorAccessor(in0_args, in0_addr, in0_tile_size);",
              "const auto in0_reader = TensorAccessor(in0_args, in0_addr, in0_tile_size);\n"
              "    const auto in0b_reader = TensorAccessor(in0_args, in2_addr, in0_tile_size);",
              "in0 accessor")
    src = sub(src, "            for (uint32_t k_block_iter = 0; k_block_iter < K_num_blocks; k_block_iter++) {",
              "            for (uint32_t pass = 0; pass < TRIMUL_TAIL_PASSES; pass++) {\n"
              "            for (uint32_t k_block_iter = 0; k_block_iter < K_num_blocks; k_block_iter++) {",
              "in0 k loop open")
    src = sub(src, "if (defer_write && k_block_iter == defer_write_k_block) {",
              "if (defer_write && pass == 0 && k_block_iter == defer_write_k_block) {",
              "in0 defer guard")
    src = sub(src, "if (reuse_block && k_block_iter == 0) {",
              "if (reuse_block && pass == 0 && k_block_iter == 0) {",
              "in0 reuse guard")
    src = sub(src, """                    read_in0_block_sync<M_block_tiles, K_block_tiles>(
                        in0_reader,""",
              """                    read_in0_block_sync<M_block_tiles, K_block_tiles>(
                        pass == 0 ? in0_reader : in0b_reader,""",
              "in0 read call")
    src = sub(src, K_LOOP_CLOSE, K_LOOP_CLOSE_NEW, "in0 k loop close")
    return HEADER + src


def patch_in1(src: str) -> str:
    src = sub(src, "const auto in1_reader = TensorAccessor(in1_args, in1_addr, in1_tile_size);",
              "const auto in1_reader = TensorAccessor(in1_args, in1_addr, in1_tile_size);\n"
              "    // TRIMUL_TAIL: pass 1's weight rides in the unused in2 slot.\n"
              "    const auto in1b_reader = TensorAccessor(in1_args, in2_addr, in1_tile_size);",
              "in1 accessor")
    src = sub(src, "            for (uint32_t k_block_iter = 0; k_block_iter < K_num_blocks; k_block_iter++) {",
              "            for (uint32_t pass = 0; pass < TRIMUL_TAIL_PASSES; pass++) {\n"
              "            for (uint32_t k_block_iter = 0; k_block_iter < K_num_blocks; k_block_iter++) {",
              "in1 k loop open")
    src = sub(src, "if (defer_write && k_block_iter == defer_write_k_block) {",
              "if (defer_write && pass == 0 && k_block_iter == defer_write_k_block) {",
              "in1 defer guard")
    src = sub(src, """                    read_in1_block_sync<K_block_tiles, N_block_tiles>(
                        in1_reader,""",
              """                    read_in1_block_sync<K_block_tiles, N_block_tiles>(
                        pass == 0 ? in1_reader : in1b_reader,""",
              "in1 read call")
    src = sub(src, K_LOOP_CLOSE, K_LOOP_CLOSE_NEW, "in1 k loop close")
    return HEADER + src


COMPUTE_PROLOGUE = """
// ---------------------------------------------------------------- TRIMUL_TAIL: the gate epilogue
#include "api/compute/eltwise_binary_sfpu.h"

#ifdef TRISC_MATH
#include "llk_math_eltwise_unary_sfpu_params.h"
#include "sfpi.h"

namespace ckernel {
namespace sfpu {
// Round DST to bf16 in the SFPU with the SAME rounding the 16-bit DST store uses, so the pack that
// follows cannot round again. Under fp32 DST the packer breaks ties away from zero where ttnn's
// binary_ng breaks them to even; E6 measured that as 0.91 % of elements at a 1.85 % tie rate.
template <int ITERATIONS = 8>
inline void _round_bf16_() {
#pragma GCC unroll 8
    for (int d = 0; d < ITERATIONS; d++) {
        sfpi::vFloat v = sfpi::dst_reg[0];
#if TRIMUL_TAIL_ROUND == 2
        // The same round-to-nearest-even by hand, in case the SFPSTOCHRND path does not land
        // where reinterpret<vFloat> expects it.
        sfpi::vUInt u = sfpi::reinterpret<sfpi::vUInt>(v);
        sfpi::vUInt lsb = (u >> 16) & 1;
        u = u + 0x7FFF;
        u = u + lsb;
        u = (u >> 16) << 16;
        sfpi::dst_reg[0] = sfpi::reinterpret<sfpi::vFloat>(u);
#else
        sfpi::dst_reg[0] = sfpi::reinterpret<sfpi::vFloat>(
            sfpi::float_to_fp16b(v, sfpi::RoundMode::NearestEven));
#endif
        sfpi::dst_reg++;
    }
}
}  // namespace sfpu
}  // namespace ckernel
#endif  // TRISC_MATH

ALWI void round_bf16_tile(uint32_t idst) {
    // `_llk_math_eltwise_unary_sfpu_params_` is a global template, not a member of `ckernel`.
    MATH((_llk_math_eltwise_unary_sfpu_params_<false>(
        ckernel::sfpu::_round_bf16_<8>, idst, (int)VectorMode::RC)));
}

// sigmoid on the bf16 branch, asked for explicitly. `sigmoid_tile` hard-wires DST_ACCUM_MODE and
// would take the accurate branch, which is not what ttnn.multiply_(..., SIGMOID) computes.
ALWI void sigmoid_bf16_tile(uint32_t idst) {
    MATH((llk_math_eltwise_unary_sfpu_sigmoid<false, false>(idst, (int)VectorMode::RC)));
}

// out = p * sigmoid(g), tile by tile, in the order and with the rounding points production uses:
// sigmoid is rounded to bf16 BEFORE the multiply (binary_ng applies an input activation in
// PREPROCESS, which packs the activated operand before the binary op unpacks it again), and the
// multiply is the SFPU one (the FPU's mul_tiles truncates the product).
void gate_block(
    uint32_t p_cb, uint32_t g_cb, uint32_t sig_cb, uint32_t out_cb, uint32_t block_num_tiles) {
    for (uint32_t t = 0; t < block_num_tiles; t++) {
        cb_reserve_back(sig_cb, 1);
        tile_regs_acquire();
        copy_tile_to_dst_init_short(g_cb);
        reconfig_data_format_srca(g_cb);
        pack_reconfig_data_format(sig_cb);
        copy_tile(g_cb, t, 0);
#if TRIMUL_TAIL_SKIP_SIGMOID == 0
        sigmoid_bf16_tile(0);
#endif
        tile_regs_commit();
        tile_regs_wait();
        pack_tile(0, sig_cb);
        tile_regs_release();
        cb_push_back(sig_cb, 1);

        cb_wait_front(sig_cb, 1);
        tile_regs_acquire();
        copy_tile_to_dst_init_short(p_cb);
        reconfig_data_format_srca(p_cb);
        pack_reconfig_data_format(out_cb);
        copy_tile(p_cb, t, 0);
        copy_tile_to_dst_init_short(sig_cb);
        copy_tile(sig_cb, 0, 1);
        mul_binary_tile_init();
        mul_binary_tile(0, 1, 0);
#if TRIMUL_TAIL_ROUND != 0
        round_bf16_tile(0);
#endif
        tile_regs_commit();
        tile_regs_wait();
        pack_tile(0, out_cb);
        tile_regs_release();
        cb_pop_front(sig_cb, 1);
    }
    cb_push_back(out_cb, block_num_tiles);
}
"""

# The wheel's per-output-block body, from the mm init down to the end of the drain, replaced
# wholesale by the two-pass form. Anchored on the whole span so a wheel change cannot be applied
# half-way.
COMPUTE_BODY_OLD = """            mm_block_init_short(
                in0_cb,
                in1_cb,
                false /*transpose*/,
                current_subblock_w /*ct_dim*/,
                current_subblock_h /*rt_dim*/,
                K_block_tiles /*kt_dim*/);
            reconfig_data_format(in1_cb, in0_cb);
            pack_reconfig_data_format(intermediate_cb);
            // Accumulation buffer
            cb_reserve_back(intermediate_cb, out_block_num_tiles);
            for (uint32_t k_block = 0; k_block < K_num_blocks; k_block++) {"""

COMPUTE_BODY_NEW = """            for (uint32_t pass = 0; pass < TRIMUL_TAIL_PASSES; pass++) {
            const uint32_t pass_cb = (pass == 0) ? p_cb : g_cb;
            mm_block_init_short(
                in0_cb,
                in1_cb,
                false /*transpose*/,
                current_subblock_w /*ct_dim*/,
                current_subblock_h /*rt_dim*/,
                K_block_tiles /*kt_dim*/);
            reconfig_data_format(in1_cb, in0_cb);
            pack_reconfig_data_format(intermediate_cb);
            // Accumulation buffer
            cb_reserve_back(intermediate_cb, out_block_num_tiles);
            for (uint32_t k_block = 0; k_block < K_num_blocks; k_block++) {"""

COMPUTE_DRAIN_OLD = """            cb_push_back(intermediate_cb, out_block_num_tiles);
            PACK((llk_pack_reconfig_l1_acc(0)));

            cb_reserve_back(out_cb, out_block_num_tiles);
#ifndef FUSE_TERNARY
            cb_wait_front(intermediate_cb, out_block_num_tiles);
#ifndef FUSE_BIAS
            copy_block(intermediate_cb, out_cb, M_block_tiles, N_block_tiles);
#else
            cb_wait_front(in2_cb, N_block_tiles);
            add_bias_block(intermediate_cb, in2_cb, out_cb, M_block_tiles, N_block_tiles);
            cb_pop_front(in2_cb, N_block_tiles);
#endif  // FUSE_BIAS
            cb_pop_front(intermediate_cb, out_block_num_tiles);

#else   // FUSE_TERNARY is set
            add_bias_and_addcmul_block(
                intermediate_cb,
                in2_cb,
                ternary_a_cb,
                ternary_b_cb,
                fused_ternary_scalar_uint,
                out_cb,
                M_block_tiles,
                N_block_tiles);
#endif  // FUSE_TERNARY
        }"""

COMPUTE_DRAIN_NEW = """            cb_push_back(intermediate_cb, out_block_num_tiles);
            PACK((llk_pack_reconfig_l1_acc(0)));

            // The fp32 accumulator -> bf16, through the wheel's own copy_block: this is the
            // identical pack that writes p_out and g_out to DRAM in production.
            cb_reserve_back(pass_cb, out_block_num_tiles);
            cb_wait_front(intermediate_cb, out_block_num_tiles);
            copy_block(intermediate_cb, pass_cb, M_block_tiles, N_block_tiles);
            cb_pop_front(intermediate_cb, out_block_num_tiles);
            }  // pass

            cb_reserve_back(out_cb, out_block_num_tiles);
            cb_wait_front(p_cb, out_block_num_tiles);
            cb_wait_front(g_cb, out_block_num_tiles);
            gate_block(p_cb, g_cb, sig_cb, out_cb, out_block_num_tiles);
            cb_pop_front(p_cb, out_block_num_tiles);
            cb_pop_front(g_cb, out_block_num_tiles);
        }"""


def patch_compute(src: str) -> str:
    src = sub(src, '#include "api/compute/eltwise_binary_sfpu.h"',
              '#include "api/compute/eltwise_binary_sfpu.h"\n' + COMPUTE_PROLOGUE,
              "compute includes")
    src = sub(src, """    constexpr uint32_t in2_cb = tt::CBIndex::c_4;
    constexpr uint32_t ternary_a_cb = tt::CBIndex::c_5;
    constexpr uint32_t ternary_b_cb = tt::CBIndex::c_6;""",
              """    constexpr uint32_t in2_cb = tt::CBIndex::c_4;
    constexpr uint32_t ternary_a_cb = tt::CBIndex::c_5;
    constexpr uint32_t ternary_b_cb = tt::CBIndex::c_6;

    // TRIMUL_TAIL: the two bf16 GEMM results and the rounded gate, one output block each.
    constexpr uint32_t p_cb = tt::CBIndex::c_4;
    constexpr uint32_t g_cb = tt::CBIndex::c_5;
    constexpr uint32_t sig_cb = tt::CBIndex::c_6;

    sigmoid_tile_init();""",
              "compute cb decls")
    src = sub(src, COMPUTE_BODY_OLD, COMPUTE_BODY_NEW, "compute block body")
    src = sub(src, COMPUTE_DRAIN_OLD, COMPUTE_DRAIN_NEW, "compute drain")
    return HEADER + src


def main() -> int:
    kd = wheel_kernel_dir()
    OUT.mkdir(parents=True, exist_ok=True)
    (OUT / "matmul_dataflow_common.hpp").write_text(
        (kd / "matmul_dataflow_common.hpp").read_text())
    (OUT / "dm_in0_sender.cpp").write_text(patch_in0((kd / "dm_in0_sender.cpp").read_text()))
    (OUT / "dm_in1_sender_out.cpp").write_text(patch_in1((kd / "dm_in1_sender_out.cpp").read_text()))
    (OUT / "compute.cpp").write_text(patch_compute((kd / "compute.cpp").read_text()))
    print(f"generated from {kd}")
    for f in ("matmul_dataflow_common.hpp", "dm_in0_sender.cpp", "dm_in1_sender_out.cpp",
              "compute.cpp"):
        print(f"  {f:28s} {len((OUT / f).read_text().splitlines())} lines")
    return 0


if __name__ == "__main__":
    sys.exit(main())
