#!/usr/bin/env python3
"""Generate `tt_bio/kernels/trimul_tail/` from the installed wheel's own minimal_matmul kernels.

F1 fuses the trimul output tail's two projections and its gate into one `generic_op`:

    production   layer_norm -> p_out = x_norm @ Wp -> g_out = x_norm_in @ Wg
                            -> multiply_(p_out, g_out, SIGMOID on b)          4P read, 3P write
    F1           layer_norm -> one kernel over (x_norm, Wp) and (x_norm_in, Wg)
                            -> sigmoid + multiply inside the core              2P read, 1P write

At the tail's block config `_MM_BLOCK[8] = (4, 8, 1, 4, 1)` the contraction is one K block
(`K_tiles == K_block_tiles == 8`), so the two GEMMs cannot interact through the cross-block L1
accumulator and the fusion is an extra PASS around the existing inner loop, not a new dataflow:

    for each output block:
        pass 0   K loop on (in0_a, in1_a) -> intermediate_cb -> copy_block -> cb_p   (bf16)
        pass 1   K loop on (in0_b, in1_b) -> intermediate_cb -> copy_block -> cb_g   (bf16)
        gate     sigmoid(cb_g) -> cb_sig ; cb_p * cb_sig -> round bf16 -> cb_out

`x_norm` and `x_norm_in` share shape, dtype, layout and memory config, so both passes share one
`TensorAccessorArgs` and differ only in the base address; likewise the two weights. The second
address rides in the unused `in2_addr` runtime slot, so the arg layout `mm_generic.rebind` depends
on is untouched.

Three rounding points are load-bearing and each mirrors what production does today. Two are E6's,
measured (`tt_bio/kernels/reblock_permute_gated/compute_reblock_permute_gated.cpp`); the third is
new to F1 and exists because F1, unlike E6, must run fp32 DST for the GEMM:

  * p and g are packed from the fp32 accumulator to bf16 through the wheel's own `copy_block`,
    which is the identical pack that writes `p_out` and `g_out` to DRAM today.
  * the sigmoid is instantiated as `llk_math_eltwise_unary_sfpu_sigmoid<false, false>` -- the
    SECOND template argument, not the descriptor's DST width. `sigmoid_tile` hard-wires
    `DST_ACCUM_MODE` and would take the accurate branch, which E6 measured as a full bf16 ulp off
    ttnn on 10.4 % of elements. The bf16 branch ends in `float_to_fp16b(result, 0)`, so what
    reaches the packer is already exactly a bf16 and the pack cannot round it again.
  * the product is rounded to bf16 IN THE SFPU by `round_bf16_tile`, with the same
    `float_to_fp16b(v, 0)`, before it is packed. Under fp32 DST the packer breaks ties away from
    zero where ttnn's 16-bit DST store breaks them to even; E6 measured that as 0.91 % of elements
    at a 1.85 % tie rate. Rounding first makes the pack exact by construction.

Regenerate after any wheel bump: the sources are read from the installed wheel, so a moved anchor
raises here instead of binding a stale kernel silently.
"""
from __future__ import annotations

import sys
from pathlib import Path

OUT = Path(__file__).resolve().parent


def wheel_kernel_dir() -> Path:
    import ttnn
    return (Path(ttnn.__file__).resolve().parent
            / "ttnn/cpp/ttnn/operations/experimental/minimal_matmul/device/kernels")


def sub(text: str, old: str, new: str, what: str, count: int = 1) -> str:
    n = text.count(old)
    if n != count:
        raise SystemExit(f"anchor '{what}' matched {n} times, expected {count}. Wheel moved.")
    return text.replace(old, new, count)


HEADER = """// SPDX-FileCopyrightText: (c) 2026 Tenstorrent USA, Inc.
//
// SPDX-License-Identifier: Apache-2.0
//
// GENERATED by tt_bio/kernels/trimul_tail/patch_trimul_tail.py from the installed wheel's
// minimal_matmul kernels. Do not edit by hand; edit the patch script and regenerate.

#ifndef TRIMUL_TAIL_PASSES
#define TRIMUL_TAIL_PASSES 2
#endif
// How the product is rounded to bf16 before it is packed: 0 leaves it to the packer (which
// breaks ties away from zero under fp32 DST), 1 uses SFPSTOCHRND round-to-nearest-even, 2 does
// the same rounding with integer arithmetic. Only 0 is known-wrong; 1 and 2 are the candidates.
#ifndef TRIMUL_TAIL_ROUND
#define TRIMUL_TAIL_ROUND 2
#endif
// Diagnostic only: drop the gate so the multiply can be scored on its own. Never set in production.
#ifndef TRIMUL_TAIL_SKIP_SIGMOID
#define TRIMUL_TAIL_SKIP_SIGMOID 0
#endif
// The epilogue. 0 is production's order, bit-exact: fp32 accumulator -> bf16 copy per pass, a
// sigmoid copy, the SFPU multiply and the integer rounding. 1 packs each pass straight out of DST
// into its bf16 CB (the sigmoid applied in DST on the gate pass) and gates with the FPU multiply:
// four unpack/pack round trips and two SFPU ops fewer per output tile, at one bf16 ULP on ties.
// 1 needs exactly one K block, which `trimul_tail.eligible` already requires. 2 is 1 plus the
// residual: the output tensor IS the pair being updated, the non-writer DM kernel reads each
// block's z tiles through the output accessor before the writer overwrites them, and the compute
// adds them to the gated product in DST, so the trailing `add_` (2P read, 1P write) is gone.
#ifndef TRIMUL_TAIL_EPI
#define TRIMUL_TAIL_EPI 0
#endif
// Both passes read the same activation (the in-projection's p and g of one x): pass 1 reuses pass
// 0's in0 block, which compute pops only after pass 1, so each activation block is read and
// forwarded down the in0 chain once instead of twice.
#ifndef TRIMUL_TAIL_SHARED_IN0
#define TRIMUL_TAIL_SHARED_IN0 0
#endif
// Diagnostic only, never set in production: a stage ablation that keeps every CB handshake and
// the in0 chain but drops one stage's work, so a timing says which stage binds. Bit 1: the in0
// injector skips its DRAM read. Bit 2: compute skips the matmul. Bit 4: the writer skips its
// DRAM writes. Bit 8: the in1 sender skips its DRAM read. The output is garbage under any bit.
#ifndef TRIMUL_TAIL_ABL
#define TRIMUL_TAIL_ABL 0
#endif
"""

SHARED_IN0_DM = (
    "                if (reuse_block && pass == 0 && k_block_iter == 0) {",
    "                if (TRIMUL_TAIL_SHARED_IN0 && pass == 1) {\n"
    "                    continue;  // pass 0's block is still in c_0\n"
    "                }\n"
    "                if (reuse_block && pass == 0 && k_block_iter == 0) {")
SHARED_IN0_COMPUTE = (
    "                if (!reuse_in0_block) {\n                    cb_pop_front(in0_cb, in0_block_num_tiles);",
    "                if (!reuse_in0_block && !(TRIMUL_TAIL_SHARED_IN0 && pass == 0)) {\n"
    "                    cb_pop_front(in0_cb, in0_block_num_tiles);")

K_LOOP_CLOSE = """                }
            }
#ifdef FUSE_BIAS"""

K_LOOP_CLOSE_NEW = """                }
            }
            }
#ifdef FUSE_BIAS"""


def patch_abl_write(src: str) -> str:
    for call in ("write_block_sync<", "write_block_sync_split<", "write_block_sync_granular<"):
        src = sub(src, f"                            {call}" if call != "write_block_sync_granular<"
                  else f"                        {call}",
                  (f"                            if (!(TRIMUL_TAIL_ABL & 4)) {call}" if call != "write_block_sync_granular<"
                   else f"                        if (!(TRIMUL_TAIL_ABL & 4)) {call}"), f"abl {call}")
    return src


def patch_in0(src: str) -> str:
    src = sub(src, "const uint32_t in0_addr = get_arg_val<uint32_t>(argidx++);",
              "const uint32_t in0_addr = get_arg_val<uint32_t>(argidx++);\n"
              "    // TRIMUL_TAIL: pass 1's activation rides in the unused in2 slot, so the runtime\n"
              "    // arg layout mm_generic.rebind depends on is unchanged.",
              "in0 addr decl")
    src = sub(src, "const auto in0_reader = TensorAccessor(in0_args, in0_addr, in0_tile_size);",
              "const auto in0_reader = TensorAccessor(in0_args, in0_addr, in0_tile_size);\n"
              "    const auto in0b_reader = TensorAccessor(in0_args, in2_addr, in0_tile_size);",
              "in0 accessor")
    src = sub(src, "            for (uint32_t k_block_iter = 0; k_block_iter < K_num_blocks; k_block_iter++) {",
              "            for (uint32_t pass = 0; pass < TRIMUL_TAIL_PASSES; pass++) {\n"
              "            for (uint32_t k_block_iter = 0; k_block_iter < K_num_blocks; k_block_iter++) {",
              "in0 k loop open")
    src = sub(src, "if (defer_write && k_block_iter == defer_write_k_block) {",
              "if (defer_write && pass == 0 && k_block_iter == defer_write_k_block) {",
              "in0 defer guard")
    src = sub(src, "if (reuse_block && k_block_iter == 0) {",
              "if (reuse_block && pass == 0 && k_block_iter == 0) {",
              "in0 reuse guard")
    src = sub(src, """                    read_in0_block_sync<M_block_tiles, K_block_tiles>(
                        in0_reader,""",
              """                    read_in0_block_sync<M_block_tiles, K_block_tiles>(
                        pass == 0 ? in0_reader : in0b_reader,""",
              "in0 read call")
    src = sub(src, "                    read_in0_block_sync<M_block_tiles, K_block_tiles>(",
              "                    if (!(TRIMUL_TAIL_ABL & 1)) read_in0_block_sync<M_block_tiles, K_block_tiles>(",
              "abl in0 read")
    src = sub(src, K_LOOP_CLOSE, K_LOOP_CLOSE_NEW, "in0 k loop close")
    src = sub(src, *SHARED_IN0_DM, "in0 shared skip")
    return HEADER + patch_resid(patch_abl_write(src))


def patch_in1(src: str) -> str:
    src = sub(src, "const auto in1_reader = TensorAccessor(in1_args, in1_addr, in1_tile_size);",
              "const auto in1_reader = TensorAccessor(in1_args, in1_addr, in1_tile_size);\n"
              "    // TRIMUL_TAIL: pass 1's weight rides in the unused in2 slot.\n"
              "    const auto in1b_reader = TensorAccessor(in1_args, in2_addr, in1_tile_size);",
              "in1 accessor")
    src = sub(src, "            for (uint32_t k_block_iter = 0; k_block_iter < K_num_blocks; k_block_iter++) {",
              "            for (uint32_t pass = 0; pass < TRIMUL_TAIL_PASSES; pass++) {\n"
              "            for (uint32_t k_block_iter = 0; k_block_iter < K_num_blocks; k_block_iter++) {",
              "in1 k loop open")
    src = sub(src, "if (defer_write && k_block_iter == defer_write_k_block) {",
              "if (defer_write && pass == 0 && k_block_iter == defer_write_k_block) {",
              "in1 defer guard")
    src = sub(src, """                    read_in1_block_sync<K_block_tiles, N_block_tiles>(
                        in1_reader,""",
              """                    read_in1_block_sync<K_block_tiles, N_block_tiles>(
                        pass == 0 ? in1_reader : in1b_reader,""",
              "in1 read call")
    src = sub(src, "                    read_in1_block_sync<K_block_tiles, N_block_tiles>(",
              "                    if (!(TRIMUL_TAIL_ABL & 8)) read_in1_block_sync<K_block_tiles, N_block_tiles>(",
              "abl in1 read")
    src = sub(src, K_LOOP_CLOSE, K_LOOP_CLOSE_NEW, "in1 k loop close")
    return HEADER + patch_resid(patch_abl_write(src))


# The bf16 rounding the product goes through before the pack. Shared with
# kernels/swiglu_fused, which patches the same wheel compute kernel at the same point and
# needs the same rounding; it renames the switch to SWIGLU_ROUND and changes nothing else.
ROUND_BF16 = """#ifdef TRISC_MATH
#include "llk_math_eltwise_unary_sfpu_params.h"
#include "sfpi.h"

namespace ckernel {
namespace sfpu {
// Round DST to bf16 in the SFPU with the SAME rounding the 16-bit DST store uses, so the pack that
// follows cannot round again. Under fp32 DST the packer breaks ties away from zero where ttnn's
// binary_ng breaks them to even; E6 measured that as 0.91 % of elements at a 1.85 % tie rate.
template <int ITERATIONS = 8>
inline void _round_bf16_() {
#pragma GCC unroll 8
    for (int d = 0; d < ITERATIONS; d++) {
        sfpi::vFloat v = sfpi::dst_reg[0];
#if TRIMUL_TAIL_ROUND == 2
        // The same round-to-nearest-even by hand, in case the SFPSTOCHRND path does not land
        // where reinterpret<vFloat> expects it.
        sfpi::vUInt u = sfpi::reinterpret<sfpi::vUInt>(v);
        sfpi::vUInt lsb = (u >> 16) & 1;
        u = u + 0x7FFF;
        u = u + lsb;
        u = (u >> 16) << 16;
        sfpi::dst_reg[0] = sfpi::reinterpret<sfpi::vFloat>(u);
#else
        sfpi::dst_reg[0] = sfpi::reinterpret<sfpi::vFloat>(
            sfpi::float_to_fp16b(v, sfpi::RoundMode::NearestEven));
#endif
        sfpi::dst_reg++;
    }
}
}  // namespace sfpu
}  // namespace ckernel
#endif  // TRISC_MATH

ALWI void round_bf16_tile(uint32_t idst) {
    // `_llk_math_eltwise_unary_sfpu_params_` is a global template, not a member of `ckernel`.
    MATH((_llk_math_eltwise_unary_sfpu_params_<false>(
        ckernel::sfpu::_round_bf16_<8>, idst, (int)VectorMode::RC)));
}
"""

COMPUTE_PROLOGUE = """
// ---------------------------------------------------------------- TRIMUL_TAIL: the gate epilogue
#include "api/compute/eltwise_binary_sfpu.h"

""" + ROUND_BF16 + """
// sigmoid on the bf16 branch, asked for explicitly. `sigmoid_tile` hard-wires DST_ACCUM_MODE and
// would take the accurate branch, which is not what ttnn.multiply_(..., SIGMOID) computes.
ALWI void sigmoid_bf16_tile(uint32_t idst) {
    MATH((llk_math_eltwise_unary_sfpu_sigmoid<false, false>(idst, (int)VectorMode::RC)));
}

// out = p * sigmoid(g), tile by tile, in the order and with the rounding points production uses:
// sigmoid is rounded to bf16 BEFORE the multiply (binary_ng applies an input activation in
// PREPROCESS, which packs the activated operand before the binary op unpacks it again), and the
// multiply is the SFPU one (the FPU's mul_tiles truncates the product).
void gate_block(
    uint32_t p_cb, uint32_t g_cb, uint32_t sig_cb, uint32_t out_cb, uint32_t block_num_tiles) {
    for (uint32_t t = 0; t < block_num_tiles; t++) {
        cb_reserve_back(sig_cb, 1);
        tile_regs_acquire();
        copy_tile_to_dst_init_short(g_cb);
        reconfig_data_format_srca(g_cb);
        pack_reconfig_data_format(sig_cb);
        copy_tile(g_cb, t, 0);
#if TRIMUL_TAIL_SKIP_SIGMOID == 0
        sigmoid_bf16_tile(0);
#endif
        tile_regs_commit();
        tile_regs_wait();
        pack_tile(0, sig_cb);
        tile_regs_release();
        cb_push_back(sig_cb, 1);

        cb_wait_front(sig_cb, 1);
        tile_regs_acquire();
        copy_tile_to_dst_init_short(p_cb);
        reconfig_data_format_srca(p_cb);
        pack_reconfig_data_format(out_cb);
        copy_tile(p_cb, t, 0);
        copy_tile_to_dst_init_short(sig_cb);
        copy_tile(sig_cb, 0, 1);
        mul_binary_tile_init();
        mul_binary_tile(0, 1, 0);
#if TRIMUL_TAIL_ROUND != 0
        round_bf16_tile(0);
#endif
        tile_regs_commit();
        tile_regs_wait();
        pack_tile(0, out_cb);
        tile_regs_release();
        cb_pop_front(sig_cb, 1);
    }
    cb_push_back(out_cb, block_num_tiles);
}
"""

# The wheel's per-output-block body, from the mm init down to the end of the drain, replaced
# wholesale by the two-pass form. Anchored on the whole span so a wheel change cannot be applied
# half-way.
COMPUTE_BODY_OLD = """            mm_block_init_short(
                in0_cb,
                in1_cb,
                false /*transpose*/,
                current_subblock_w /*ct_dim*/,
                current_subblock_h /*rt_dim*/,
                K_block_tiles /*kt_dim*/);
            reconfig_data_format(in1_cb, in0_cb);
            pack_reconfig_data_format(intermediate_cb);
            // Accumulation buffer
            cb_reserve_back(intermediate_cb, out_block_num_tiles);
            for (uint32_t k_block = 0; k_block < K_num_blocks; k_block++) {"""

COMPUTE_BODY_NEW = """            for (uint32_t pass = 0; pass < TRIMUL_TAIL_PASSES; pass++) {
            const uint32_t pass_cb = (pass == 0) ? p_cb : g_cb;
            mm_block_init_short(
                in0_cb,
                in1_cb,
                false /*transpose*/,
                current_subblock_w /*ct_dim*/,
                current_subblock_h /*rt_dim*/,
                K_block_tiles /*kt_dim*/);
            reconfig_data_format(in1_cb, in0_cb);
            pack_reconfig_data_format(intermediate_cb);
            // Accumulation buffer
            cb_reserve_back(intermediate_cb, out_block_num_tiles);
            for (uint32_t k_block = 0; k_block < K_num_blocks; k_block++) {"""

COMPUTE_DRAIN_OLD = """            cb_push_back(intermediate_cb, out_block_num_tiles);
            PACK((llk_pack_reconfig_l1_acc(0)));

            cb_reserve_back(out_cb, out_block_num_tiles);
#ifndef FUSE_TERNARY
            cb_wait_front(intermediate_cb, out_block_num_tiles);
#ifndef FUSE_BIAS
            copy_block(intermediate_cb, out_cb, M_block_tiles, N_block_tiles);
#else
            cb_wait_front(in2_cb, N_block_tiles);
            add_bias_block(intermediate_cb, in2_cb, out_cb, M_block_tiles, N_block_tiles);
            cb_pop_front(in2_cb, N_block_tiles);
#endif  // FUSE_BIAS
            cb_pop_front(intermediate_cb, out_block_num_tiles);

#else   // FUSE_TERNARY is set
            add_bias_and_addcmul_block(
                intermediate_cb,
                in2_cb,
                ternary_a_cb,
                ternary_b_cb,
                fused_ternary_scalar_uint,
                out_cb,
                M_block_tiles,
                N_block_tiles);
#endif  // FUSE_TERNARY
        }"""

COMPUTE_DRAIN_NEW = """            cb_push_back(intermediate_cb, out_block_num_tiles);
            PACK((llk_pack_reconfig_l1_acc(0)));

            // The fp32 accumulator -> bf16, through the wheel's own copy_block: this is the
            // identical pack that writes p_out and g_out to DRAM in production.
            cb_reserve_back(pass_cb, out_block_num_tiles);
            cb_wait_front(intermediate_cb, out_block_num_tiles);
            copy_block(intermediate_cb, pass_cb, M_block_tiles, N_block_tiles);
            cb_pop_front(intermediate_cb, out_block_num_tiles);
            }  // pass

            cb_reserve_back(out_cb, out_block_num_tiles);
            cb_wait_front(p_cb, out_block_num_tiles);
            cb_wait_front(g_cb, out_block_num_tiles);
            gate_block(p_cb, g_cb, sig_cb, out_cb, out_block_num_tiles);
            cb_pop_front(p_cb, out_block_num_tiles);
            cb_pop_front(g_cb, out_block_num_tiles);
        }"""


def patch_compute(src: str) -> str:
    src = sub(src, '#include "api/compute/eltwise_binary_sfpu.h"',
              '#include "api/compute/eltwise_binary_sfpu.h"\n' + COMPUTE_PROLOGUE,
              "compute includes")
    src = sub(src, """    constexpr uint32_t in2_cb = tt::CBIndex::c_4;
    constexpr uint32_t ternary_a_cb = tt::CBIndex::c_5;
    constexpr uint32_t ternary_b_cb = tt::CBIndex::c_6;""",
              """    constexpr uint32_t in2_cb = tt::CBIndex::c_4;
    constexpr uint32_t ternary_a_cb = tt::CBIndex::c_5;
    constexpr uint32_t ternary_b_cb = tt::CBIndex::c_6;

    // TRIMUL_TAIL: the two bf16 GEMM results and the rounded gate, one output block each.
    constexpr uint32_t p_cb = tt::CBIndex::c_4;
    constexpr uint32_t g_cb = tt::CBIndex::c_5;
    constexpr uint32_t sig_cb = tt::CBIndex::c_6;

    sigmoid_tile_init();""",
              "compute cb decls")
    src = sub(src, COMPUTE_BODY_OLD, COMPUTE_BODY_NEW, "compute block body")
    src = sub(src, COMPUTE_DRAIN_OLD, COMPUTE_DRAIN_NEW, "compute drain")
    return HEADER + patch_compute_epi(src)


# TRIMUL_TAIL_EPI == 2: the residual read, in whichever DM kernel is not the output writer.
RESID_READ = """#if TRIMUL_TAIL_EPI == 2
            // TRIMUL_TAIL: the residual. The output IS the pair tensor being updated (written in
            // place), so this block's z tiles are read through the output accessor before the
            // writer overwrites them: same tile ids as write_block_sync_granular, one row of
            // N_block_tiles per M tile, into c_7.
            if constexpr (!is_output_writer) {
                constexpr uint32_t cb_id_resid = tt::CBIndex::c_7;
                cb_reserve_back(cb_id_resid, M_block_tiles * N_block_tiles);
                const uint32_t resid_wp = get_write_ptr(cb_id_resid);
                for (uint32_t m_id = 0; m_id < M_block_tiles; m_id++) {
                    const uint32_t mt = m_tile + m_id;
                    if (mt >= m_tile_end || mt >= out_shape.logical_d0) {
                        break;
                    }
                    uint32_t wp = resid_wp + m_id * N_block_tiles * out_tile_size;
                    for (uint32_t nt = n_tile; nt < n_tile_end && nt < out_shape.logical_d1; nt++) {
                        noc_async_read_tile(mt * out_shape.logical_d1 + nt, std::get<0>(outputs_tuple), wp);
                        wp += out_tile_size;
                    }
                }
                noc_async_read_barrier();
                cb_push_back(cb_id_resid, M_block_tiles * N_block_tiles);
            }
#endif
"""
RESID_ANCHOR = """            }
            }
#ifdef FUSE_BIAS
            if constexpr (!is_output_writer) {"""


def patch_resid(src: str) -> str:
    return sub(src, RESID_ANCHOR, RESID_ANCHOR.replace("#ifdef FUSE_BIAS", RESID_READ + "#ifdef FUSE_BIAS", 1),
               "resid read")


# TRIMUL_TAIL_EPI == 1 (see HEADER). Applied after the anchors above, on their output.
GATE_FPU = """
// out = p * sig, the FPU multiply over one output block, four tiles per DST acquire (the fp32
// half-sync capacity). Used by TRIMUL_TAIL_EPI >= 1 only.
// With RESID (TRIMUL_TAIL_EPI == 2) it adds the residual block in resid_cb in DST: out = z + p * sig.
template <bool RESID>
void gate_block_fpu(
    uint32_t p_cb, uint32_t sig_cb, uint32_t resid_cb, uint32_t out_cb, uint32_t block_num_tiles) {
    reconfig_data_format(p_cb, sig_cb);
    pack_reconfig_data_format(out_cb);
    for (uint32_t t0 = 0; t0 < block_num_tiles; t0 += 4) {
        const uint32_t n = (block_num_tiles - t0) < 4 ? (block_num_tiles - t0) : 4;
        tile_regs_acquire();
        mul_tiles_init(p_cb, sig_cb);
        for (uint32_t i = 0; i < n; i++) {
            mul_tiles(p_cb, sig_cb, t0 + i, t0 + i, i);
        }
        if constexpr (RESID) {
            binary_dest_reuse_tiles_init<EltwiseBinaryType::ELWADD, EltwiseBinaryReuseDestType::DEST_TO_SRCA>(
                resid_cb);
            for (uint32_t i = 0; i < n; i++) {
                binary_dest_reuse_tiles<EltwiseBinaryType::ELWADD, EltwiseBinaryReuseDestType::DEST_TO_SRCA>(
                    resid_cb, t0 + i, i);
            }
        }
        tile_regs_commit();
        tile_regs_wait();
        for (uint32_t i = 0; i < n; i++) {
            pack_tile(i, out_cb);
        }
        tile_regs_release();
    }
    cb_push_back(out_cb, block_num_tiles);
}
"""


def patch_compute_epi(src: str) -> str:
    src = sub(src, "\n// ---------------------------------------------------------------- TRIMUL_TAIL: the gate epilogue\n",
              "\n// ---------------------------------------------------------------- TRIMUL_TAIL: the gate epilogue\n",
              "epi prologue marker")
    src = sub(src, "    cb_push_back(out_cb, block_num_tiles);\n}\n",
              "    cb_push_back(out_cb, block_num_tiles);\n}\n" + GATE_FPU, "epi gate_block_fpu")
    src = sub(src, "    const uint32_t subblock_w) {",
              "    const uint32_t subblock_w,\n"
              "    const bool tail_sigmoid = false) {", "epi matmul_blocks signature")
    src = sub(src, """                in1_index += full_N_block_tiles;
            }
            tile_regs_commit();""", """                in1_index += full_N_block_tiles;
            }
            if (tail_sigmoid) {
                for (uint32_t i = 0; i < subblock_h * subblock_w; i++) {
                    sigmoid_bf16_tile(i);
                }
            }
            tile_regs_commit();""", "epi sigmoid in DST")
    src = sub(src, """            const uint32_t pass_cb = (pass == 0) ? p_cb : g_cb;
            mm_block_init_short(""", """            const uint32_t pass_cb = (pass == 0) ? p_cb : g_cb;
#if TRIMUL_TAIL_EPI >= 1
            const uint32_t mm_out_cb = pass_cb;
#else
            const uint32_t mm_out_cb = intermediate_cb;
#endif
            mm_block_init_short(""", "epi mm_out_cb")
    src = sub(src, """            reconfig_data_format(in1_cb, in0_cb);
            pack_reconfig_data_format(intermediate_cb);
            // Accumulation buffer
            cb_reserve_back(intermediate_cb, out_block_num_tiles);
            for (uint32_t k_block = 0; k_block < K_num_blocks; k_block++) {""",
              """            reconfig_data_format(in1_cb, in0_cb);
            pack_reconfig_data_format(mm_out_cb);
            // Accumulation buffer
            cb_reserve_back(mm_out_cb, out_block_num_tiles);
            for (uint32_t k_block = 0; k_block < K_num_blocks; k_block++) {""", "epi reserve")
    src = sub(src, """                matmul_blocks(
                    in0_cb,
                    in1_cb,
                    intermediate_cb,
                    current_M_block_tiles,
                    current_N_block_tiles,
                    N_block_tiles,
                    K_block_tiles,
                    current_subblock_h,
                    current_subblock_w);""", """                matmul_blocks(
                    in0_cb,
                    in1_cb,
                    mm_out_cb,
                    current_M_block_tiles,
                    current_N_block_tiles,
                    N_block_tiles,
                    K_block_tiles,
                    current_subblock_h,
                    current_subblock_w,
                    TRIMUL_TAIL_EPI >= 1 && pass == 1);""", "epi matmul_blocks call")
    src = sub(src, """            cb_push_back(intermediate_cb, out_block_num_tiles);
            PACK((llk_pack_reconfig_l1_acc(0)));

            // The fp32 accumulator -> bf16, through the wheel's own copy_block: this is the
            // identical pack that writes p_out and g_out to DRAM in production.
            cb_reserve_back(pass_cb, out_block_num_tiles);
            cb_wait_front(intermediate_cb, out_block_num_tiles);
            copy_block(intermediate_cb, pass_cb, M_block_tiles, N_block_tiles);
            cb_pop_front(intermediate_cb, out_block_num_tiles);
            }  // pass
""", """            cb_push_back(mm_out_cb, out_block_num_tiles);
            PACK((llk_pack_reconfig_l1_acc(0)));

#if TRIMUL_TAIL_EPI == 0
            // The fp32 accumulator -> bf16, through the wheel's own copy_block: this is the
            // identical pack that writes p_out and g_out to DRAM in production.
            cb_reserve_back(pass_cb, out_block_num_tiles);
            cb_wait_front(intermediate_cb, out_block_num_tiles);
            copy_block(intermediate_cb, pass_cb, M_block_tiles, N_block_tiles);
            cb_pop_front(intermediate_cb, out_block_num_tiles);
#endif
            }  // pass
""", "epi drain")
    src = sub(src, "            gate_block(p_cb, g_cb, sig_cb, out_cb, out_block_num_tiles);\n",
              "#if TRIMUL_TAIL_EPI == 1\n"
              "            gate_block_fpu<false>(p_cb, g_cb, g_cb, out_cb, out_block_num_tiles);\n"
              "#elif TRIMUL_TAIL_EPI == 2\n"
              "            cb_wait_front(tt::CBIndex::c_7, out_block_num_tiles);\n"
              "            gate_block_fpu<true>(p_cb, g_cb, tt::CBIndex::c_7, out_cb, out_block_num_tiles);\n"
              "            cb_pop_front(tt::CBIndex::c_7, out_block_num_tiles);\n"
              "#else\n"
              "            gate_block(p_cb, g_cb, sig_cb, out_cb, out_block_num_tiles);\n"
              "#endif\n", "epi gate call")
    src = sub(src, *SHARED_IN0_COMPUTE, "shared in0 pop")
    src = sub(src, "                matmul_blocks(\n                    in0_cb,",
              "                if (!(TRIMUL_TAIL_ABL & 2)) matmul_blocks(\n                    in0_cb,", "abl matmul")
    return src


def main() -> int:
    kd = wheel_kernel_dir()
    OUT.mkdir(parents=True, exist_ok=True)
    (OUT / "matmul_dataflow_common.hpp").write_text(
        (kd / "matmul_dataflow_common.hpp").read_text())
    (OUT / "dm_in0_sender.cpp").write_text(patch_in0((kd / "dm_in0_sender.cpp").read_text()))
    (OUT / "dm_in1_sender_out.cpp").write_text(patch_in1((kd / "dm_in1_sender_out.cpp").read_text()))
    (OUT / "compute.cpp").write_text(patch_compute((kd / "compute.cpp").read_text()))
    print(f"generated from {kd}")
    for f in ("matmul_dataflow_common.hpp", "dm_in0_sender.cpp", "dm_in1_sender_out.cpp",
              "compute.cpp"):
        print(f"  {f:28s} {len((OUT / f).read_text().splitlines())} lines")
    return 0


if __name__ == "__main__":
    sys.exit(main())
