"""Fill the wh-galaxy exemption reasons this campaign's re-records left TODO.

Two flags account for all 19, on four models, and neither is a lever that got tuned at one
size and forgotten at another -- which is the thing the size-ladder arm exists to catch, so
saying so needs the mechanism and not a shrug.

Every reason is written as "<evidence>: <judgement>" with the evidence half generated by the
gate's own _size_ladder_reason_evidence, so the head matches SIZE_LADDER_EVIDENCE_HEADS and
the next re-record regenerates the numbers instead of carrying them verbatim. Same shape as
perf/sizeladder_p300c/reasons_boltz2.py.

Run from the repo root with the tt-bio venv:
    PYTHONPATH=$PWD python3 perf/sizeladder_whgalaxy/reasons_whgalaxy.py
"""
import importlib.util, json, pathlib, sys

ROOT = pathlib.Path(__file__).resolve().parent.parent.parent
spec = importlib.util.spec_from_file_location("rg", ROOT / "scripts" / "release_gate.py")
rg = importlib.util.module_from_spec(spec)
sys.modules["rg"] = rg
spec.loader.exec_module(rg)

CARD = "tt-galaxy-wh-l"

TRANSITION_H_CHUNK = (
    "the height RAISE is the Blackhole branch and there is no Wormhole one. "
    "tt_bio/tenstorrent.py scores this counter as served only when the derived height comes "
    "out ABOVE the shipped base, and on a small grid it cannot: the small-grid raise is "
    "scoped to 256 < c <= 384 and this call site is c=128, so the height stays at the base "
    "(base-unraised) or the per-core L1 cap pulls it under (ratio-shrunk). The Blackhole "
    "elif takes the same budget the other way round -- there the measured L1 ceiling sits "
    "well above the base, so it raises -- which is why p150a and p300c read 1.0 at every "
    "rung and this board reads 0.0 from 512 up. 256 serves because the base is reached "
    "there. Nothing declines on a size the lever was tuned for; the lever has no Wormhole "
    "raise to decline"
)

TRANSPOSE_L1_RESIDENT = (
    "it is a fit test, not a tuned constant, and the pair tensor stops fitting one rung "
    "earlier on this grid. PAIR_TRANSPOSE_VIA_ROW_MAJOR takes over the same calls exactly: "
    "TRANSPOSE_L1_RESIDENT serves every call at 256 and 512 and the row-major route serves "
    "none, then the two swap, and from 896 up the row-major route serves all of them. One "
    "of the pair serves at every rung, so no transpose is unoptimised at any size. The "
    "Blackhole cards make the same swap at 768; 8x9 Wormhole cores hold less L1, so the "
    "headroom test flips at 640"
)

# model -> flag -> the rungs where it is dark on this card.
J = {
    "openfold3": {
        "TRANSITION_H_CHUNK":    ("512", "640", "768", "896", "1024"),
        "TRANSPOSE_L1_RESIDENT": ("896", "1024"),
    },
    "openbind": {
        "TRANSITION_H_CHUNK":    ("512", "640", "768", "896"),
        "TRANSPOSE_L1_RESIDENT": ("896",),
    },
    "protenix-v1": {
        "TRANSITION_H_CHUNK":    ("512", "640", "768", "896", "1024"),
        "TRANSPOSE_L1_RESIDENT": ("640", "768", "896", "1024"),
    },
}
WHY = {"TRANSITION_H_CHUNK": TRANSITION_H_CHUNK,
       "TRANSPOSE_L1_RESIDENT": TRANSPOSE_L1_RESIDENT}

# nesso1/256 REBLOCK_PERMUTE is the fourth model's single TODO and is NOT written here: it
# declines on window_BufferType.L1 x2, gated_window_BufferType.L1 x1, back_l1_src_narrow x1
# -- four calls, three different clauses, none of them the two mechanisms above. It needs
# its own reading of the trimul path and gets no invented sentence from this file.

def main() -> int:
    frag_dir = ROOT / "docs" / "size_ladder_baseline.d"
    written = 0
    for model, flags in sorted(J.items()):
        path = frag_dir / f"{model}.json"
        data = json.loads(path.read_text())
        entry = data["cards"][CARD]["models"][model]
        for flag, rungs in sorted(flags.items()):
            for rung in rungs:
                e = entry["levers"][rung][flag]
                assert rg._size_ladder_dark(e), f"{model}/{rung}/{flag} is not dark"
                e["reason"] = rg._size_ladder_reason_evidence(e) + ": " + WHY[flag]
                written += 1
        path.write_text(json.dumps(data, indent=2) + "\n")
    print(f"wrote {written} exemption reasons on {CARD}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
