#!/usr/bin/env python3
"""Generate `tt_bio/kernels/swiglu_fused/compute.cpp` from the installed wheel's minimal_matmul.

The pair Transition's SwiGLU is three ops today:

    production   x_1 = silu(x_norm @ W1) ; x_2 = x_norm @ W2 ; multiply_(x_1, x_2)
    fused        one kernel over (x_norm, W1) and (x_norm, W2), silu and the multiply in the core

c14-radical measured why this needs a kernel rather than a rewrite. Concatenating W1 and W2 into
one [128, 1024] projection is 1.340x on the matmuls themselves (0.06317 vs 0.08466 ms), but ttnn
has no view, so `multiply_` makes the caller pay two `ttnn.slice` calls worth 0.03302 ms against
the 0.02149 ms the merge returns, and the whole shipped-pattern arm comes out 1.076x SLOWER. The
per-op fixed term is 50.8 % of a single N=512 call at this key, and a fused kernel is the only way
to collect it without an un-concatenate.

The two-pass data movement starts from `trimul_tail`'s fork -- it already reads a second
(activation, weight) pair out of the unused `in2_addr` runtime slot -- and then diverges on the one
thing SwiGLU does differently: both passes contract the SAME activation. So pass 1 does not read
in0 at all, and the compute kernel holds pass 0's in0 block across the pass boundary.

That is a correctness fix before it is a saving. Wrapping the wheel's k loop in a pass loop and
leaving its in0 reuse alone DEADLOCKS the device whenever `N_blocks_per_core > 1`: the reader
pushes 3 in0 blocks per m block (pass 0 and pass 1 of n block 0, pass 1 of n block 1, the wheel's
reuse skipping only pass 0 of n block 1) while the compute kernel pops 2, so a 2-block CB leaks
one block per m block and `cb_reserve_back` blocks forever. MEASURED on qb1 node 0, 2026-09-18:
the host spun in `completion_queue_wait_front` for 11 minutes at 100 % of one core. trimul_tail
never hit it because at its (8, 8) key `N_blocks_per_core` is 1, so the wheel's reuse never arms.
Reading in0 once per m block and popping it once per m block is what makes the two counts equal,
and it needs `K_num_blocks == 1` -- which the allow-list already guarantees and a `static_assert`
now enforces at JIT-build time rather than as a hang.

At the Transition's block config `_MM_BLOCK[(4, 16)] = (4, 4, 1, 4, 1)` the contraction
is one K block (K_tiles == K_block_tiles == 4), so the two GEMMs cannot interact through the
cross-block L1 accumulator and the fusion is an extra pass around the existing inner loop:

    for each output block:
        pass 0   K loop on (x_norm, W1) -> intermediate_cb -> copy_block_silu -> cb_a  (bf16)
        pass 1   K loop on (x_norm, W2) -> intermediate_cb -> copy_block      -> cb_b  (bf16)
        gate     cb_a * cb_b -> round bf16 -> cb_out

Two rounding points, each mirroring what production does today:

  * pass 0 applies `silu_tile` to the fp32 accumulator and packs to bf16. That is the identical
    call `ttnn.linear(activation="silu")` makes on the identical fp32 DST, so pass 0 is
    production's fc1 with the same SFPU branch (`silu_tile` takes DST_ACCUM_MODE, and the arm it
    replaces compiles with the same fp32_dest_acc_en).
  * the product is rounded to bf16 IN THE SFPU by `round_bf16_tile` before it is packed, for the
    reason `patch_trimul_tail.ROUND_BF16` records: under fp32 DST the packer breaks ties away from
    zero where ttnn's binary_ng breaks them to even.

Regenerate after any wheel bump: the source is read from the installed wheel, so a moved anchor
raises here instead of binding a stale kernel silently.
"""
from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "trimul_tail"))
import patch_trimul_tail as PT          # noqa: E402  the shared wheel reader and patch helpers

OUT = Path(__file__).resolve().parent

HEADER = """// SPDX-FileCopyrightText: (c) 2026 Tenstorrent USA, Inc.
//
// SPDX-License-Identifier: Apache-2.0
//
// GENERATED by tt_bio/kernels/swiglu_fused/patch_swiglu_fused.py from the installed wheel's
// minimal_matmul kernels. Do not edit by hand; edit the patch script and regenerate.
//
// The data movement starts from trimul_tail's two-pass fork and diverges on one thing: SwiGLU's
// two passes contract the same activation, so pass 1 does not read in0 and the compute kernel
// holds pass 0's block across the pass boundary. Pushes and pops have to agree or the CB
// deadlocks -- see the patch script for the measured failure.

// How the product is rounded to bf16 before it is packed: 0 leaves it to the packer (which breaks
// ties away from zero under fp32 DST), 2 does binary_ng's round-to-nearest-even in integers.
#ifndef SWIGLU_ROUND
#define SWIGLU_ROUND 2
#endif
"""

PROLOGUE = """
// -------------------------------------------------------------- SWIGLU_FUSED: the gate epilogue
#include "api/compute/eltwise_binary_sfpu.h"

""" + PT.ROUND_BF16.replace("TRIMUL_TAIL_ROUND", "SWIGLU_ROUND") + """

// The wheel's own copy_block with production's fused activation in it: fp32 accumulator -> silu
// -> bf16. `ttnn.linear(activation="silu")` applies this same `silu_tile` to the same fp32 DST
// before the same pack, so pass 0 is production's fc1.
void copy_block_silu(
    uint32_t in_cb, uint32_t out_cb, uint32_t M_block_tiles, uint32_t N_block_tiles) {
    copy_tile_to_dst_init_short(in_cb);
    reconfig_data_format_srca(in_cb);
    pack_reconfig_data_format(out_cb);

    uint32_t tile_id = 0;
    for (uint32_t m = 0; m < M_block_tiles; m++) {
        for (uint32_t n = 0; n < N_block_tiles; n++) {
            acquire_dst();
            copy_tile(in_cb, tile_id, 0);
            silu_tile(0);
            pack_tile(0, out_cb);
            release_dst();
            tile_id++;
        }
        cb_push_back(out_cb, N_block_tiles);
    }
}

// out = silu(fc1) * fc2, tile by tile. `a_cb` already holds silu(fc1) in bf16, so this is exactly
// the `multiply_` production issues, on the SFPU (the FPU's mul_tiles truncates the product) with
// the product rounded to bf16 before the pack.
void swiglu_block(uint32_t a_cb, uint32_t b_cb, uint32_t out_cb, uint32_t block_num_tiles) {
    for (uint32_t t = 0; t < block_num_tiles; t++) {
        tile_regs_acquire();
        copy_tile_to_dst_init_short(a_cb);
        reconfig_data_format_srca(a_cb);
        pack_reconfig_data_format(out_cb);
        copy_tile(a_cb, t, 0);
        copy_tile_to_dst_init_short(b_cb);
        copy_tile(b_cb, t, 1);
        mul_binary_tile_init();
        mul_binary_tile(0, 1, 0);
#if SWIGLU_ROUND != 0
        round_bf16_tile(0);
#endif
        tile_regs_commit();
        tile_regs_wait();
        pack_tile(0, out_cb);
        tile_regs_release();
    }
    cb_push_back(out_cb, block_num_tiles);
}
"""

CB_DECLS_OLD = """    constexpr uint32_t in2_cb = tt::CBIndex::c_4;
    constexpr uint32_t ternary_a_cb = tt::CBIndex::c_5;
    constexpr uint32_t ternary_b_cb = tt::CBIndex::c_6;"""

CB_DECLS_NEW = CB_DECLS_OLD + """

    // SWIGLU_FUSED: the two bf16 GEMM results, one output block each.
    constexpr uint32_t a_cb = tt::CBIndex::c_4;
    constexpr uint32_t b_cb = tt::CBIndex::c_5;"""

BODY_OLD = """            mm_block_init_short(
                in0_cb,
                in1_cb,
                false /*transpose*/,"""

BODY_NEW = """            for (uint32_t pass = 0; pass < 2; pass++) {
            const uint32_t pass_cb = (pass == 0) ? a_cb : b_cb;
""" + BODY_OLD

DRAIN_NEW = """            cb_push_back(intermediate_cb, out_block_num_tiles);
            PACK((llk_pack_reconfig_l1_acc(0)));

            // The fp32 accumulator -> bf16, through the wheel's own copy_block, with silu folded
            // into pass 0's pack the way production's fc1 folds it.
            cb_reserve_back(pass_cb, out_block_num_tiles);
            cb_wait_front(intermediate_cb, out_block_num_tiles);
            if (pass == 0) {
                silu_tile_init();
                copy_block_silu(intermediate_cb, pass_cb, M_block_tiles, N_block_tiles);
            } else {
                copy_block(intermediate_cb, pass_cb, M_block_tiles, N_block_tiles);
            }
            cb_pop_front(intermediate_cb, out_block_num_tiles);
            }  // pass

            cb_reserve_back(out_cb, out_block_num_tiles);
            cb_wait_front(a_cb, out_block_num_tiles);
            cb_wait_front(b_cb, out_block_num_tiles);
            swiglu_block(a_cb, b_cb, out_cb, out_block_num_tiles);
            cb_pop_front(a_cb, out_block_num_tiles);
            cb_pop_front(b_cb, out_block_num_tiles);
        }"""


KARG_OLD = """    constexpr uint32_t subblock_w = get_compile_time_arg_val(7);"""

KARG_NEW = KARG_OLD + """

    // SWIGLU_FUSED: one K block is the whole simplification. The two GEMMs must not interact
    // through the cross-block L1 accumulator, and in0 is held across the pass boundary, which
    // needs exactly one in0 block live per output block. A wider key is a kernel change, not a
    // table entry -- fail the build instead of hanging the card.
    static_assert(K_num_blocks == 1, "swiglu_fused requires K_tiles == K_block_tiles");"""

POP_OLD = """                if (!reuse_in0_block) {
                    cb_pop_front(in0_cb, in0_block_num_tiles);
                }
                cb_pop_front(in1_cb, in1_block_num_tiles);
                reuse_in0_block = false;"""

POP_NEW = """                // SWIGLU_FUSED: in0 is the SAME activation on both passes, so it is held
                // across the pass boundary and popped once, after pass 1. The reader skips its
                // pass-1 read to match; pushes and pops have to agree or the CB deadlocks.
                if (pass == 1) {
                    if (!reuse_in0_block) {
                        cb_pop_front(in0_cb, in0_block_num_tiles);
                    }
                    reuse_in0_block = false;
                }
                cb_pop_front(in1_cb, in1_block_num_tiles);"""

IN0_SKIP_OLD = """                if (reuse_block && pass == 0 && k_block_iter == 0) {"""

IN0_SKIP_NEW = """                if (pass == 1) {
                    // SWIGLU_FUSED: pass 1 contracts the same activation as pass 0, whose block is
                    // still at the front of the CB because the compute kernel has not popped it.
                    // Reading it again pushes a copy nobody pops.
                    continue;
                }
                if (reuse_block && pass == 0 && k_block_iter == 0) {"""


def patch_in0(src: str) -> str:
    return PT.sub(PT.patch_in0(src), IN0_SKIP_OLD, IN0_SKIP_NEW, "in0 pass-1 skip")


def patch_compute(src: str) -> str:
    src = PT.sub(src, '#include "api/compute/eltwise_binary_sfpu.h"',
                 '#include "api/compute/eltwise_binary_sfpu.h"\n' + PROLOGUE,
                 "compute includes")
    src = PT.sub(src, CB_DECLS_OLD, CB_DECLS_NEW, "compute cb decls")
    src = PT.sub(src, BODY_OLD, BODY_NEW, "compute block body")
    src = PT.sub(src, KARG_OLD, KARG_NEW, "compute k args")
    src = PT.sub(src, POP_OLD, POP_NEW, "compute in0 pop")
    src = PT.sub(src, PT.COMPUTE_DRAIN_OLD, DRAIN_NEW, "compute drain")
    return HEADER + src


def main() -> int:
    kd = PT.wheel_kernel_dir()
    OUT.mkdir(parents=True, exist_ok=True)
    (OUT / "matmul_dataflow_common.hpp").write_text(
        (kd / "matmul_dataflow_common.hpp").read_text())
    (OUT / "dm_in0_sender.cpp").write_text(patch_in0((kd / "dm_in0_sender.cpp").read_text()))
    (OUT / "dm_in1_sender_out.cpp").write_text(
        PT.patch_in1((kd / "dm_in1_sender_out.cpp").read_text()))
    (OUT / "compute.cpp").write_text(patch_compute((kd / "compute.cpp").read_text()))
    print(f"generated from {kd}")
    for f in ("matmul_dataflow_common.hpp", "dm_in0_sender.cpp", "dm_in1_sender_out.cpp",
              "compute.cpp"):
        print(f"  {f:28s} {len((OUT / f).read_text().splitlines())} lines")
    return 0


if __name__ == "__main__":
    sys.exit(main())
