#!/usr/bin/env python3
"""Render perf/bhdesign/*.jsonl into the campaign's evidence log.

The log is GENERATED, never hand-kept: a row typed next to the run it describes drifts from it,
and this sweep's whole claim is that the artifact decides the verdict. Annotations that a row
cannot carry (what a FAIL was actually caused by) live in NOTES.md and are appended verbatim.

    python3 perf/bhdesign/render_sweep.py > perf/bhdesign/sweep.log
"""
import json
import pathlib
import sys

HERE = pathlib.Path(__file__).resolve().parent
AXIS = {
    "esmc": "MAX_SEQUENCE (residues in the longest single sequence)",
    "saprot": "MAX_SEQUENCE (residues in the longest single sequence)",
    "rfd3": "DESIGN_TOTAL (motif crop + designed length)",
    "pxdesign": "DESIGN_TARGET (conditioned target residues; binder held at 80)",
    "boltzgen": "TARGET ATOMS (its trunk Pairformer's triangle attention is atom-denominated)",
}


def axis_of(model: str) -> str:
    for k, v in AXIS.items():
        if model.startswith(k):
            return v
    return "?"


def main() -> int:
    rows = []
    for f in sorted(HERE.glob("*.jsonl")):
        for line in f.read_text().splitlines():
            if line.strip():
                rows.append(json.loads(line))
    rows.sort(key=lambda r: (r["model"], r["size"]))

    out = [
        "# Blackhole p150a capacity sweep, design + embedding family (qb1, physical card 1)",
        "# GENERATED by perf/bhdesign/render_sweep.py from perf/bhdesign/*.jsonl. Do not hand-edit.",
        "# One rung per SUBPROCESS through the shipped CLI. PASS means the ARTIFACT landed with the",
        "# right shape; an exit code of 0 is not evidence and is not what is read here.",
        "# Rows marked (rescored) re-read an artifact an earlier row already ran; the 0.0s is a",
        "# re-read, not a fold. Both rows are kept, so a corrected verdict shows its correction.",
        "#",
        "# The axis is per model and they are not the same axis:",
    ]
    for k, v in AXIS.items():
        out.append(f"#   {k:<10} {v}")
    out += ["#", "# columns: model  size  verdict  mechanism  wall_s  artifact", ""]

    last = None
    for r in rows:
        if r["model"] != last:
            out.append("")
            last = r["model"]
        extra = f" target_atoms={r['target_atoms']}" if "target_atoms" in r else ""
        # A rescored row re-reads an artifact an earlier row already paid the card time for, so
        # its 0.0s is a re-read and not a fold. Say so, or the log reads as a free result.
        if r.get("rescored"):
            extra += " (rescored, timed row above)"
        out.append(f"{r['model']:<12} {r['size']:<6} {r['verdict']:<8} "
                   f"{r['mechanism']:<14} {r['wall_s']:>6.1f}s{extra}  "
                   f"{json.dumps(r['artifact'])}")

    npass = sum(1 for r in rows if r["verdict"] == "PASS")
    out += ["", f"# {len(rows)} rungs, {npass} PASS, {len(rows) - npass} not PASS, "
                f"{len({r['model'] for r in rows})} models."]

    notes = HERE / "NOTES.md"
    if notes.is_file():
        out += ["", "# --- annotations: what a row cannot say about itself ---" + "-" * 40, ""]
        out += ["# " + l if l.strip() else "#" for l in notes.read_text().splitlines()]

    print("\n".join(out))
    return 0


if __name__ == "__main__":
    sys.exit(main())
