#!/usr/bin/env python3
"""SaProt parity vs the reference HuggingFace EsmForMaskedLM on real weights.

Reproduce the numbers in docs/saprot-parity.md. Loads the same HF checkpoint into both
the ttnn port (tt_bio.saprot) and the reference (transformers EsmForMaskedLM), runs an
identical fused-AA+3Di input through both, and reports per-residue embedding + MLM-logits
PCC. The golden reference outputs are cached by scripts/ref_saprot_golden.py.

Usage:
    FOLDSEEK_BIN=... TT_VISIBLE_DEVICES=0 python scripts/saprot_parity.py --model saprot-650m
"""
import argparse, os, sys, math, numpy as np, torch

def pcc(a, b):
    a = a.ravel().astype(np.float64); b = b.ravel().astype(np.float64)
    a = a - a.mean(); b = b - b.mean()
    den = math.sqrt((a * a).sum()) * math.sqrt((b * b).sum())
    return float((a * b).sum() / den) if den > 0 else 0.0

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--model", default="saprot-650m", choices=["saprot-35m", "saprot-650m", "saprot-1.3b"])
    ap.add_argument("--seq", default=None, help="bare AA sequence (default: ubiquitin 76)")
    args = ap.parse_args()
    name_tag = {"saprot-35m": "35M", "saprot-650m": "650M", "saprot-1.3b": "1.3B"}[args.model]
    sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))
    os.environ.setdefault("TT_VISIBLE_DEVICES", "0")
    os.environ.setdefault("TT_BIO_LOGICAL_DEVICE_ID", "0")
    from tt_bio import saprot, esmc
    ubq = args.seq or "MQIFVKTLTGKTITLEVEPSDTIENVKAKIQDKEGIPPDQQRLIFAGKQLEDGRTLSDYNIQKESTLHLVLRLRGG"
    struc = (saprot.FOLDSEEK_STRUC_VOCAB[:-1] * 6)[: len(ubq)]
    # Reference (HF) — cache golden if absent.
    golden = f"scripts/_golden_saprot_{name_tag}.npz"
    # The golden files are generated by scripts/ref_saprot_golden.py and live outside the
    # repo (they are large and reference-only); fall back to the shared saprot-work copy.
    if not os.path.isfile(golden):
        golden = os.path.expanduser(f"~/saprot-work/golden_{name_tag}.npz")
    g = np.load(golden)
    ids = g["input_ids"].tolist()
    # ttnn port forward (padded to a bucket, real positions masked).
    BUCKET = esmc.BUCKET
    L = len(ids); Lb = ((L + BUCKET - 1) // BUCKET) * BUCKET
    input_ids = torch.tensor([ids + [1] * (Lb - L)], dtype=torch.long)
    attn = torch.zeros(1, Lb, Lb, dtype=torch.float32); attn[0, :, L:] = float("-inf")
    kv = torch.ones(1, 1, Lb, 1, dtype=torch.float32); kv[0, :, L:, :] = 0.0
    em = torch.ones(1, Lb, 1, dtype=torch.float32); em[0, L:, :] = 0.0
    print(f"[{name_tag}] loading {args.model} (L={L} Lb={Lb})...", flush=True)
    m = saprot.load_saprot(args.model)
    logits, emb = m(input_ids, attn, kv, em)
    emb = emb[0, :L].numpy().astype(np.float32)
    logits = logits[0, :L].numpy().astype(np.float32)
    g_emb = g["emb"].astype(np.float32); g_logits = g["logits"].astype(np.float32)
    print(f"[{name_tag}] emb PCC     = {pcc(emb, g_emb):.6f}")
    print(f"[{name_tag}] logits PCC = {pcc(logits, g_logits):.6f}")
    print(f"[{name_tag}] emb[:3,0]   {emb[:3,0]}  (ref {g_emb[:3,0]})")

if __name__ == "__main__":
    main()
